name: NPM Lockfile Changes
on: [pull_request, workflow_dispatch]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: NPM Lockfile Changes
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: '[Test] NPM Lockfile Changes Detached Package'
        uses: ./
        with:
          path: tests/ci/package-lock.json
          token: ${{ secrets.GITHUB_TOKEN }}
